# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instavector', '0002_auto_20201020_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='instavector.Profile'),
            preserve_default=False,
        ),
    ]
