# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instavector', '0002_auto_20201019_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='instavector.Profile'),
        ),
    ]
