# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instavector', '0003_auto_20201020_0745'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('follower', 'followed')]),
        ),
    ]
