# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instavector', '0006_auto_20201019_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
